### ISSUE TITLE
Invalid mex File

### ISSUE THREAD

**Issue by KlaymenGC** [Lansbergen/BaslerCamDriver_Installation_Tutorial_Windows_7#1]
Hello,

Thanks for the tutorial! I followed the tutorial and successfully built the libraries and the functions, but when I use the functions, it says:
 `Invalid MEX-file 'C:\Documents\MATLAB\BaslerCamDriver-419332a\baslerFindCameras.mexw64': The specified module could not be found.` 
Any ideas?

Thanks in advance!

**Comment by Lansbergen** [comment]
If you build the libraries and functions `baslerFindCameras.mexw64` should be located in the root of `Matlab_BaslerCamDriver` maybe the files are located somewhere else as you have a different root for the cam driver directory. 
Not sure, but do you have the actual mexw64 file in your directory?

**Comment by KlaymenGC** [comment]
Yes the actual mexw64 files are in the root of matlab_baslerdriver, and I'm using the SDK 7.1 to build them.

**Comment by Lansbergen** [comment]
Hard to say. I would check the Pylon root directories in your win environment variables. but then again, if this is not correct I would not expect it to build anyway.
did you tried the `make clean` command and then build it again?

The information the error provides is very 'limited', I couldn't tell right now.

**Comment by KlaymenGC** [comment]
I did try to build it again but without `make clean`, I'll let you know if this would help

**Comment by KlaymenGC** [comment]
After make clean, it works :)
